[config]
schemaVersion = "0.0.1"

[package]
namespace = "Trodi"
name = "BloodyCore"
versionNumber = "1.2.2"
description = "Bloody.Core a help library for mod development. It must be installed if any mod uses it."
websiteUrl = "https://github.com/oscarpedrero/BloodyCore"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
deca-Bloodstone = "0.2.2"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["1-0-update", "mods", "server"]